# Generated by Django 4.0.1 on 2022-10-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_food', models.CharField(max_length=150)),
                ('calorie', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=5, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=5, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
    ]
