# Generated by Django 4.0.1 on 2022-05-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfood',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addfood',
            name='fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addfood',
            name='protein',
            field=models.IntegerField(default=0),
        ),
    ]
