# Generated by Django 4.0.1 on 2022-10-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_addfood_carbs_alter_addfood_fats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfood',
            name='carbs',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='addfood',
            name='fats',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='addfood',
            name='protein',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
