# Generated by Django 4.0.1 on 2022-06-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_addfood_carbs_addfood_fats_addfood_protein'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_limit', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='addfood',
            name='name_of_food',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
