# Generated by Django 4.0.1 on 2022-06-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_calorielimit_alter_addfood_name_of_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfood',
            name='calorie',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='addfood',
            name='carbs',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='addfood',
            name='fats',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='addfood',
            name='name_of_food',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addfood',
            name='protein',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
