# Generated by Django 4.0.1 on 2022-06-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_addfood_calorie_alter_addfood_carbs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalorieLimit',
        ),
        migrations.AlterField(
            model_name='addfood',
            name='calorie',
            field=models.IntegerField(),
        ),
    ]
