# Generated by Django 4.0.1 on 2022-06-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_calorielimit_alter_addfood_calorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFoodLunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_food', models.CharField(max_length=200)),
                ('calorie', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=4, max_digits=20)),
                ('fats', models.DecimalField(decimal_places=4, max_digits=20)),
                ('carbs', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
    ]
