# Generated by Django 4.0.1 on 2022-10-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_addfoodlunch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddFoodLunch',
        ),
        migrations.AlterField(
            model_name='addfood',
            name='carbs',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='addfood',
            name='fats',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='addfood',
            name='name_of_food',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='addfood',
            name='protein',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
